<?php

namespace App\Models\Application;

use App\Http\Controllers\Application\ApplicationRun;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Application extends Model
{
    use HasFactory;

    protected $fillable =
        [
            'user_id',
            'application_name_id',
            'application_status_id',
            'identification',
        ];

    /*
     * Передаем модель для обработки задания
     * Если модель создается или обновляется не через builder необходимо вызвать событие
     * ApplicationEvent и передать в него модель, слушатель ApplicationRunListener
     * выполнит дальнейшие действия по созданию класса и передачи модели
     * */

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model){
            $r = new ApplicationRun();
            $r($model);
        });

        static::updating(function ($model){
            $r = new ApplicationRun();
            $r($model);
        });
    }

    public function ApplicationName(): BelongsTo
    {
        return $this->belongsTo(ApplicationName::class);
    }

    public function ApplicationStatus(): BelongsTo
    {
        return $this->belongsTo(ApplicationStatus::class);
    }
}
